vich_uploader:
    db_driver: orm

    mappings:
       sousCategorie:
            uri_prefix: /images/sousCategories
            upload_destination: '%kernel.project_dir%/public/images/sousCategories'
